services:
  web:
    build: 
      context: .
      dockerfile: docker/Dockerfile.heroku
    environment:
      - PORT=${PORT}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - EXTERNAL_ORIGIN=https://${HEROKU_APP_NAME}.herokuapp.com
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - keycloak
      - ozmadb
      - ozma-report-generator

  keycloak:
    image: keycloak/keycloak:25.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=${DATABASE_URL}
      - KC_HOSTNAME_STRICT=false
      - KC_PROXY=edge
      - KC_HTTP_RELATIVE_PATH=/auth
    command: ["start", "--optimized"]

  ozmadb:
    image: ozmaio/ozmadb:master
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_AUTHORITY=https://${HEROKU_APP_NAME}.herokuapp.com/auth/realms/ozma
      - AUTH_METADATA_ADDRESS=http://keycloak:8080/auth/realms/ozma/.well-known/openid-configuration
      - AUTH_REQUIRE_HTTPS_METADATA=false

  ozma-report-generator:
    image: ozmaio/ozma-report-generator:master
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_CLIENT_ID=ozma-report-generator
      - ORIGIN=https://${HEROKU_APP_NAME}.herokuapp.com
      - PATH_BASE=/report-generator
      - OZMA_DB_URL=http://ozmadb:5000
      - AUTH_AUTHORITY=https://${HEROKU_APP_NAME}.herokuapp.com/auth/realms/ozma
      - AUTH_METADATA_ADDRESS=http://keycloak:8080/auth/realms/ozma/.well-known/openid-configuration
      - AUTH_REQUIRE_HTTPS_METADATA=false 
