FROM node:20-alpine AS build

WORKDIR /app

COPY . .
RUN corepack enable
RUN --mount=type=cache,target=/root/.yarn YARN_NODE_LINKER=node-modules yarn install --immutable
RUN NODE_OPTIONS=--max-old-space-size=1536 YARN_NODE_LINKER=node-modules yarn build

FROM caddy

# https://kofi.sexy/blog/zero-downtime-render-disk
RUN setcap -r /usr/bin/caddy
COPY --from=build /app/dist /usr/share/caddy
COPY ./docker/Caddyfile.ozma /etc/caddy/Caddyfile
