FROM keycloak/keycloak:25.0

COPY ./docker/keycloak-realm.json /etc/keycloak/realm.json
COPY ./docker/keycloak-entrypoint.sh /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["start", "--import-realm"]